### ISSUE TITLE
Have elix remind people about things

### ISSUE THREAD

**Issue by stevegrossi** [indyelixir/elix#7]
### Example API

```
Steve: @Elix remind me to check the thing in an hour
Elix: Okay, @Steve. In one hour I'll remind you to check the thing
... 1 hour later
Elix: @Steve, you asked me to remind you to check the thing now.
```

### Features

- natural-language alternatives (always start with "remind me" though), e.g.
  - remind me to X in TIME
  - remind me in TIME to X
  - remind me about X in TIME
  - remind me of X in time
- relative and absolute times, "in 3 hours" vs. "at 9am tomorrow"
  - [timex](https://github.com/bitwalker/timex/#quickfast-introduction) does relative times
- show all scheduled reminders with the ability to cancel?

### Technical

- actually, this gets real tricky: how do we get Hedwig to send a spontaneous message?
- probably means we'll need a time zone in the environment
- we could do this pretty trivially with [`Process.send_after/3`](http://elixir-lang.org/docs/stable/elixir/Process.html#send_after/3) but if the process crashed we'll lose all the pending reminders. Probably want to store these in Redis keyed to the reminder date/time and query them every second or something.

**Comment by janxious** [comment]
> we could do this pretty trivially with Process.send_after/3 but if the process crashed we'll lose all the pending reminders. Probably want to store these in Redis keyed to the reminder date/time and query them every second or something.

What if redis was the store, but you just stored the state in a loop in elixir. If you crash, you can reload state from redis without having to do a bunch of network traffic.

**Comment by stevegrossi** [comment]
That seems like an optimal solution. Practically, I think the Redis calls will be pretty fast so I'm not too worried about performance, but it would be nice to be able to keep on truckin' even if Redis goes down temporarily or has hiccups.
